#!/usr/bin/env bash
ZIP_FILE=project4.zip
REQUIRED_FILES="convert.sh q1.js q2.js q3.js q4.js q5.js laureate.php"
OPTIONAL_FILES="README.txt"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#error function
function error_exit()
{
   echo -e "ERROR: $1" 1>&2
   exit 1
}

# make sure running in container
if [ `whoami` != "cs143" ]; then
    error_exit "You need to run this script within the container"
fi

# change to the directory where the script is located
cd ${DIR}

# check file existence
if [ -f ${ZIP_FILE} ]; then
    rm -f ${ZIP_FILE}
fi

# check the existence of the required files
for FILE in ${REQUIRED_FILES}
do
    if [ ! -f ${FILE} ]; then
        echo "ERROR: Cannot find ${FILE} in ${DIR}" 1>&2
        exit 1
    fi
done

echo "zip ${ZIP_FILE} -x p4_package p4_test \*.json \*.import @ -r ."
zip ${ZIP_FILE} -x p4_package p4_test \\*.json \\*.import @ -r .
if [ $? -ne 0 ]; then
    error_exit "Create ${ZIP_FILE} failed, check for error messages in console."
fi

echo "[SUCCESS] Created '$DIR/${ZIP_FILE}'"

exit 0
